FROM python:3.10-slim

WORKDIR /usr/src/app
COPY ./requirements.txt /usr/src/app

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

COPY ./app/consumer.py /usr/src/app
COPY ./app/cassandra_client.py /usr/src/app

CMD ["python3", "consumer.py"]